config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'devise', :controllers=> {registrations: 'registrations'}


  resources :posts, only:[:new, :create, :index, :destroy]
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "posts#index"

   

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :index, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :title, :post)
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ActionController::Base
    

    private

    def sign_up_params
        params.require(:user).permit(:username, :password, :email, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :password, :email, :password_confirmation, :current_password)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    private

    def sign_up_params
        params.require(:user).permit(:username, :password, :email, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :password, :email, :password_confirmation, :current_password)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" %>
    <%= javascript_importmap_tags %>
     <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <% if flash[:notice]%>
      <div class="notification global-notification is-success">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification global-notification is-danger">    
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5 dark">Members Only!</h1>
        <% end %>

        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="navbar-menu navbar-end">
          <div class="navbar-item">
            <%= link_to 'New Post', root_path, class:" button is-dark ml-2"%>
            <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item ml-2" %>
            <%= link_to "Logout", destroy_user_session_path, method: :get, class:"navbar-item ml-2" %>
          </div>
        </div>
      <%else%>
        <div class="navbar-menu navbar-end">
          <div class="navbar-item">
            <%= link_to 'Login', new_user_session_path, class:"navbar-item"%>
            <%= link_to 'Sign Up', new_user_registration_path, class:"navbar-item" %>
          </div>       
        </div>
      <% end %>
      </div> 
    </nav>
    
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/posts/_feed.html.erb
<div class="column is-half">

    <%= render "form" %>

    <% @posts.each do | post | %>
     <div class="box"> 
      <article class="media">
        <div class="media-content">
          <div class="content mb-2">
            <% if user_signed_in? %>
              <%= post.user.try(:username) %>
            <% else %>
              <h3> Anonymous </h3>
            <% end %>
            <br>
             <strong> <%= post.title %> </strong> <br>
             <p> <%= post.post %> </p>
          </div>
        </div>
        <div class="media-right">
          <% if user_signed_in? && current_user.id == post.user_id %>
            <%= link_to post,  data: { turbo_method: :delete ,turbo_confirm: 'Are you sure?' } do %>
              <button class="delete"></button>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
    <% end %>
</div>

app/views/posts/_form.html.erb
<article class="column"> 
  <div class="container">
    <%= simple_form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label class="label">Title</label>
    </div>
    <div class="field-body">
      <div class="field">

        <div class="control">
          <%= f.text_field :title, autofocus:true, label: false, class:"input is-medium" %>
        </div>
      </div>
    </div>
    </div>
    <div class="field is-horizontal pt-5">
      <div class="field-label is-normal"> 
        <label class="label">Post</label>
      </div>
      <div class="field-body">
        <div class="field">
          <div class="control">
            <%= f.text_area :post, label: false, class:"textarea input is-medium" %>
          </div>
        </div>
    </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label">
        <!-- Left empty for spacing -->
      </div>
       <div class="field-body">
        <div class="field">
          <div class="control">
            <%= f.button :submit, class: "button is-warning mb-5" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</article>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>User:</strong>
    <%= @post.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= @post.post %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1 class="subtitle">Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns">
       <%= render "feed" %>    
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>


</div>

app/views/users/edit.html.erb
<h1 class="subtitle">Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>